### PR TITLE
47 dashboard page

### LINKED ISSUE #47: Dashboard Page
**Task Title**
Create Dashboard Page

**Task description**
Create a dashboard page that displays a user's borrowed items, lent items, purchases, sold items, and owned items.

**Screenshot**
Image

[Figma Link](https://www.figma.com/file/FYZIsFvg1rLu50UnriUN8Y/Student-Store-Project?type=design&node-id=79-554&mode=design&t=i0O5DvjMg4XZDRs4-4)

### PR DESCRIPTION
**Pull request by Bolphunga**
**Changes made**:
Added dashboard page fetching product data on the server side.
Added mobile view to navbar.

**Screenshots**
Desktop view:
image

Mobile view:
image

image

# Related Issue
Resolves #47

### CODE REVIEW

**Review by medshk — COMMENTED** [review]
can u add screenshots please for both desktop and mobile

**Review by 0m3ga13 — APPROVED** [review]
I think it may be approved but we have to add a component for the user

**Comment by medshk** [comment]
the styling does not match the design requirements in the Figma file , please fix them , plus the page should be functional don't display dummy data

**Comment by Bolphunga** [comment]
The requested changes have been implemented. Dummy data now needs to be replaced by new server data.

**Review by samiraTbl — APPROVED** [review]
well done

**Pull request merged**
