### PR TITLE
feat(donate page): added donation page

### LINKED ISSUE #73: donation page
Task Title
Donation page 

**Task description**
create  a page  about donation

**Screenshots**
image

**Link to the component on Figma**
https://www.figma.com/file/FYZIsFvg1rLu50UnriUN8Y/Student-Store-Project?type=design&node-id=627-504&mode=dev

### PR DESCRIPTION
**Pull request by Bolphunga**
Changes made:
Added a donation page with three donation options;

Notes:
The cover image is a placeholder. It can be changed later.
Fonts are not being fetched properly and are subject to change.

**Screenshots**

image
image
image
image

Resolves #73

# Related Issue

- Resolve #73

### CODE REVIEW

**Comment by 0m3ga13** [comment]
it does look good but I am experiencing an issue in mobile view here:




also any Ideas how can we make the donations functional?
cc: @Emybel @medshk @samiraTbl

**Comment by Bolphunga** [comment]
It's fixed. Thanks for the feedback.

**Review by 0m3ga13 — APPROVED** [review]
Great Job

**Review by medshk — APPROVED** [review]
PR permitted , well done

**Pull request merged**
