### PR TITLE
52 product display

### LINKED ISSUE #52: Product Display
**Task title**
Create Product Display component.

**Task description**
Create a dynamic component that displays images of the product as well as its information, buy/borrow buttons, and the seller's contact information.

**Screenshots**
image

[Figma Link](https://www.figma.com/file/FYZIsFvg1rLu50UnriUN8Y/Student-Store-Project?type=design&node-id=43-113&mode=design&t=o9at4z6V7ZPmhbxP-4)

### PR DESCRIPTION
**Pull request by Emybel**
### Pull Request: Feature - Product Display Component

**Description**:
This pull request addresses the task of creating a "Product Display" component related to the single product page in Branch 52-product-display.

**Changes Made:**
In this branch, the following changes were made:

1. Implemented a dynamic image slider to showcase product images.
2. Added user profile information, including profile picture, name, location, and institution of the student.
3. Include a description text for the product and its category.
4. Added "Buy" and "Borrow" buttons to enable users to take action.
5. Displayed personal information about the user (seller or lender), including email and phone number, to facilitate contact.

**Purpose:**
This component enhances the user experience by providing a comprehensive view of the product and its associated details, making it easier for potential buyers or borrowers to make informed decisions and contact the seller or lender.

**Testing:**
1. The component is not responsive yet, and this is acknowledged as an ongoing task.
2. The component has not been connected to Firestore yet, and this integration will be addressed in future updates.

**Additional Notes:**
I am open to feedback and suggestions for further improvements to this component.

**Screenshot:**

product-display-component

# Related Issue

- Resolve #52

### CODE REVIEW

**Comment by 0m3ga13** [comment]
Great job @Emybel , can you add screenshots in the description please?

**Review by 0m3ga13 — APPROVED** [review]
you did an amazing job,  I guess next we will have to:

-  add the href in the category Link, @medshk  please make sure to add searchParms in the products page.

- As you said fix the mobile layout

- I feel there is some nuisance with the navbar, either in the width (mobile view) or while working on the web view we have to add "fixing this" to our to-dos
cc: @samiraTbl

**Comment by Emybel** [comment]
I added the screenshot to the first comment, and I'm working on the mobile view (responsiveness). It should be ready by tomorrow Inchallah.

**Review by medshk — APPROVED** [review]
PR permitted well done

**Pull request merged**
