### PR TITLE
fix: fixed sizing with dashboard and donate pages

### LINKED ISSUE #80: Resize the elements
**Task title**
Fix the sizes of the dashboard and donate pages.

**Task description**
The dashboard and donate pages are too big and need to be resized.

### LINKED ISSUE #101: (Product Item) Fix sizing
the Product Item is pushing the Navlinks, fix it and make the sizes more dynamic.

**screenshots**
image
image

### PR DESCRIPTION
**Pull request by Bolphunga**
**Changes made:**
Remodeled the donate page.
Made the dashboard elements a bit smaller.
Fixed some small responsiveness issues.

**Screenshots**
image
image

image
image

Resolves #80 #101 

# Related Issue

- Resolve #80

### CODE REVIEW

**Review by 0m3ga13 — DISMISSED** [review]
ALL GOOD

**Review by 0m3ga13 — COMMENTED** [review]
your code is good, but please check #101  fix it and come back here

**Review by 0m3ga13 — APPROVED** [review]
well done!

**Review by medshk — APPROVED** [review]
PR permitted,

**Pull request merged**
