### PR TITLE
46 edit profile page

### LINKED ISSUE #46: Edit Profile Page
**Task Title**
Create Edit Profile Page

**Task description**
Create a page that allows the user to edit the personal information on their profile.

**Screenshot**
Image

[Figma Link](https://www.figma.com/file/FYZIsFvg1rLu50UnriUN8Y/Student-Store-Project?type=design&node-id=79-555&mode=design&t=i0O5DvjMg4XZDRs4-4)

### PR DESCRIPTION
**Pull request by 0m3ga13**
we finished the form for profile page

**suggestions**: add a field for the user, to check if the user is Fully Registred, if not he can't publish items neither buy items.

**screenshots**: 
image

PS: I added a security form component but it's not functional, we have to create another issue for it 

fix #46

### CODE REVIEW

**Review by Bolphunga — APPROVED** [review]
Great job.

**Review by medshk — COMMENTED** [review]
The form should take full screen height, footer should not be appearent

**Comment by 0m3ga13** [comment]
> The form should take full screen height, footer should not be appearent
@medshk  check this: 

https://www.figma.com/file/FYZIsFvg1rLu50UnriUN8Y/Student-Store-Project?type=design&node-id=79-555&mode=design&t=uxj7MgttH7fFXqyy-4

**Review by medshk — APPROVED** [review]
PR permitted, good job

**Pull request merged**
